name: Your First Action

on:
  push:
    branches: [main]
env:
  BRANCH_NAME: amartya3
jobs:
  first_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          path: out.csv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: generate-out.csv
        run: |
          python convert.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'amartyanambiar'
          git config --global user.email 'amartyanambiar@gmail.com'
          git checkout -b $BRANCH_NAME
          git add out.csv
          git commit -m 'Update output'
          git push -u origin $BRANCH_NAME
