name: Your First Action

on:
  push:
    branches: [main]

jobs:
  first_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: generate-out.csv
        run: |
          python convert.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'amartyanambiar'
          git config --global user.email 'amartyanambiar@gmail.com'
          git add out.csv
          git commit -m 'Update output'
          git checkout -b output
          git pull origin output
          git push origin output
